# Generated by Django 3.2.5 on 2021-07-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название источника информации (Coinbase, bloomberg, etc)')),
                ('href', models.CharField(max_length=200, verbose_name='Ссылка на главную')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание источника информации')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название акции (BTC, ETH, AAPL)')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст статьи')),
                ('href', models.CharField(max_length=200, verbose_name='Ссылка на статью')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга')),
                ('wrote_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выхода статьи')),
                ('title_score_2', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('title_score_3', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('title_score_4', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('text_score_2', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('text_score_3', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('text_score_4', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка алгоритма скоринга')),
                ('human_classification', models.CharField(choices=[('POSITIVE', 'Самовывоз'), ('NEGATIVE', 'Доставка курьером')], default='POSITIVE', max_length=100, verbose_name='Оценка')),
                ('sourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.source')),
            ],
        ),
    ]
