# Generated by Django 3.2.5 on 2021-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_score_2',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_score_3',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_score_4',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_2',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_3',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_4',
            field=models.FloatField(verbose_name='Оценка алгоритма скоринга'),
        ),
    ]
