# Generated by Django 3.2.5 on 2021-07-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210724_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sourse',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.source'),
        ),
        migrations.AlterField(
            model_name='article',
            name='human_classification',
            field=models.CharField(choices=[('POSITIVE', 'Положительная'), ('NEGATIVE', 'Отрицательная')], default='POSITIVE', max_length=100, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parsed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время парсинга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_score_2',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_score_3',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_score_4',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_2',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_3',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_score_4',
            field=models.FloatField(null=True, verbose_name='Оценка алгоритма скоринга'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wrote_at',
            field=models.DateTimeField(null=True, verbose_name='Время выхода статьи'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.theme'),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(verbose_name='Описание источника информации'),
        ),
        migrations.AlterField(
            model_name='source',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.theme'),
        ),
    ]
